### ISSUE TITLE
Might get ignored but support for OpenGL 4.4?

### ISSUE THREAD

**Issue by Endy3032** [Wieku/danser-go#187]
This issue might get ignored but its better than nothing. My CPU is an intel i5-5575R (Windows dual booted iMac) which only supports OpenGL 4.4 max. Danser requires `GL_ARB_direct_state_access` which is only available from OpenGL 4.5 onwards. If it is possible could it work without needing DSA or OGL 4.5+ is a must? Still, this is still an extremely cool project and I just wanna use it for fun on my old imac. Hopefully I can run it one day :D

**Comment by Endy3032** [comment]
Log if needed
```
2021/09/03 12:52:05 Initializing GLFW...
2021/09/03 12:52:07 GLFW initialized!
2021/09/03 12:52:07 panic: Your GPU does not support one or more required OpenGL extensions: [GL_ARB_direct_state_access]. Please update your graphics drivers or upgrade your GPU
2021/09/03 12:52:07 goroutine 1 [running, locked to thread]:
2021/09/03 12:52:07 main.extensionCheck()
2021/09/03 12:52:07     D:/danser-dist/danser-go/main.go:722 +0x1ca
2021/09/03 12:52:07 main.run.func1()
2021/09/03 12:52:07     D:/danser-dist/danser-go/main.go:406 +0x190c
2021/09/03 12:52:07 github.com/faiface/mainthread.Call.func1()
2021/09/03 12:52:07     C:/Users/Wieku/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:63 +0x26
2021/09/03 12:52:07 github.com/faiface/mainthread.Run(0x7ff77c8b6a70)
2021/09/03 12:52:07     C:/Users/Wieku/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:44 +0xc9
2021/09/03 12:52:07 main.main()
2021/09/03 12:52:07     D:/danser-dist/danser-go/main.go:922 +0x112
2021/09/03 12:52:07
2021/09/03 12:52:07 goroutine 23 [chan receive]:
2021/09/03 12:52:07 github.com/faiface/mainthread.Call(0x7ff77c8b6a68)
2021/09/03 12:52:07     C:/Users/Wieku/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:66 +0xb1
2021/09/03 12:52:07 main.run()
2021/09/03 12:52:07     D:/danser-dist/danser-go/main.go:93 +0x25
2021/09/03 12:52:07 github.com/faiface/mainthread.Run.func1()
2021/09/03 12:52:07     C:/Users/Wieku/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:37 +0x26
2021/09/03 12:52:07 created by github.com/faiface/mainthread.Run
2021/09/03 12:52:07     C:/Users/Wieku/go/pkg/mod/github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:36 +0xbd
2021/09/03 12:52:07
2021/09/03 12:52:07 goroutine 21 [IO wait]:
2021/09/03 12:52:07 internal/poll.runtime_pollWait(0x2327ca626d8, 0x72)
2021/09/03 12:52:07     C:/Program Files/Go/src/runtime/netpoll.go:229 +0x89
2021/09/03 12:52:07 internal/poll.(*pollDesc).wait(0xc671c3202a854aea, 0x34c9f9562def61e0, 0x0)
2021/09/03 12:52:07     C:/Program Files/Go/src/internal/poll/fd_poll_runtime.go:84 +0x32
2021/09/03 12:52:07 internal/poll.execIO(0xc000288018, 0x7ff77c8b6988)
2021/09/03 12:52:07     C:/Program Files/Go/src/internal/poll/fd_windows.go:175 +0xe5
2021/09/03 12:52:07 internal/poll.(*FD).Read(0xc000288000, {0xc00020a000, 0xe03, 0xe03})
2021/09/03 12:52:07     C:/Program Files/Go/src/internal/poll/fd_windows.go:441 +0x25f
2021/09/03 12:52:07 net.(*netFD).Read(0xc000288000, {0xc00020a000, 0xe03, 0xc00013e640})
2021/09/03 12:52:07     C:/Program Files/Go/src/net/fd_posix.go:56 +0x29
2021/09/03 12:52:07 net.(*conn).Read(0xc000006020, {0xc00020a000, 0x7ff77c532b79, 0xc0001837f0})
2021/09/03 12:52:07     C:/Program Files/Go/src/net/net.go:183 +0x45
2021/09/03 12:52:07 crypto/tls.(*atLeastReader).Read(0xc0001464c8, {0xc00020a000, 0x0, 0x7ff77c16b44d})
2021/09/03 12:52:07     C:/Program Files/Go/src/crypto/tls/conn.go:777 +0x3d
2021/09/03 12:52:07 bytes.(*Buffer).ReadFrom(0xc000060cf8, {0x7ff77c943a00, 0xc0001464c8})
2021/09/03 12:52:07     C:/Program Files/Go/src/bytes/buffer.go:204 +0x98
2021/09/03 12:52:07 crypto/tls.(*Conn).readFromUntil(0xc000060a80, {0x2327ca627c0, 0xc000006020}, 0xc00020a005)
2021/09/03 12:52:07     C:/Program Files/Go/src/crypto/tls/conn.go:799 +0xe5
2021/09/03 12:52:07 crypto/tls.(*Conn).readRecordOrCCS(0xc000060a80, 0x0)
2021/09/03 12:52:07     C:/Program Files/Go/src/crypto/tls/conn.go:606 +0x112
2021/09/03 12:52:07 crypto/tls.(*Conn).readRecord(...)
2021/09/03 12:52:07     C:/Program Files/Go/src/crypto/tls/conn.go:574
2021/09/03 12:52:07 crypto/tls.(*Conn).Read(0xc000060a80, {0xc000228000, 0x1000, 0xc000121c20})
2021/09/03 12:52:07     C:/Program Files/Go/src/crypto/tls/conn.go:1277 +0x16f
2021/09/03 12:52:07 bufio.(*Reader).Read(0xc000121bc0, {0xc000218498, 0x9, 0xc00021e4a0})
2021/09/03 12:52:07     C:/Program Files/Go/src/bufio/bufio.go:227 +0x1b4
2021/09/03 12:52:07 io.ReadAtLeast({0x7ff77c9438e0, 0xc000121bc0}, {0xc000218498, 0x9, 0x9}, 0x9)
2021/09/03 12:52:07     C:/Program Files/Go/src/io/io.go:328 +0x9a
2021/09/03 12:52:07 io.ReadFull(...)
2021/09/03 12:52:07     C:/Program Files/Go/src/io/io.go:347
2021/09/03 12:52:07 net/http.http2readFrameHeader({0xc000218498, 0x9, 0xc000213140}, {0x7ff77c9438e0, 0xc000121bc0})
2021/09/03 12:52:07     C:/Program Files/Go/src/net/http/h2_bundle.go:1553 +0x6e
2021/09/03 12:52:07 net/http.(*http2Framer).ReadFrame(0xc000218460)
2021/09/03 12:52:07     C:/Program Files/Go/src/net/http/h2_bundle.go:1811 +0x95
2021/09/03 12:52:07 net/http.(*http2clientConnReadLoop).run(0xc000183fa0)
2021/09/03 12:52:07     C:/Program Files/Go/src/net/http/h2_bundle.go:8428 +0x165
2021/09/03 12:52:07 net/http.(*http2ClientConn).readLoop(0xc000178180)
2021/09/03 12:52:07     C:/Program Files/Go/src/net/http/h2_bundle.go:8350 +0x79
2021/09/03 12:52:07 created by net/http.(*http2Transport).newClientConn
2021/09/03 12:52:07     C:/Program Files/Go/src/net/http/h2_bundle.go:7302 +0xb45
```

**Comment by Wieku** [comment]
No, I won't downgrade it after raising requirements for 0.5.0. Blame Intel for shitty gpu support because 2010s NVIDIA cards can run it.

**Comment by Wieku** [comment]
There's a high chance that MESA on Linux will have that extension though

**Comment by Endy3032** [comment]
Ok Thanks for the info!
