### ISSUE TITLE
[Bug] Panic when using escaped spaces in string.

### ISSUE THREAD

**Issue by MierenManz** [Wieku/danser-go#230]
**Describe the bug**
Commands like `danser -replay ~/.local/share/osu-stable/Replays/MierenMans\ -\ Various\ Artists\ -\ Alternator\ Marathon\ \[5.\ A\ CRUEL\ ANGEL\'S\ THESIS\ -\ YOKO\ TAKAHASHI\ \(256\ BPM\)\]\ \(2022-03-05\)\ Osu.osr`
Panic's on linux (possibly other OS' aswell, not tested) due to the the argument parser not being able to properly parse the whole path. It ends parsing on `~/.local/share/osu-stable/Replays/MierenMans` because the parser ignores the escaped space

**Screenshots**

**Logs**
```
2022/03/05 22:52:59 danser-go version: 0.6.8
2022/03/05 22:52:59 panic: open /home/skyler/.local/share/osu-stable/Replays/MierenMans: no such file or directory
2022/03/05 22:52:59 goroutine 1 [running, locked to thread]:
2022/03/05 22:52:59 main.run.func1()
2022/03/05 22:52:59 	github.com/wieku/danser-go/main.go:183 +0x2e58
2022/03/05 22:52:59 github.com/faiface/mainthread.Call.func1()
2022/03/05 22:52:59 	github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:63 +0x26
2022/03/05 22:52:59 github.com/faiface/mainthread.Run(0x562c94b6f078)
2022/03/05 22:52:59 	github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:44 +0xc9
2022/03/05 22:52:59 main.main()
2022/03/05 22:52:59 	github.com/wieku/danser-go/main.go:905 +0x1c8
2022/03/05 22:52:59 
2022/03/05 22:52:59 goroutine 35 [chan receive]:
2022/03/05 22:52:59 github.com/faiface/mainthread.Call(0x562c94b6f070)
2022/03/05 22:52:59 	github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:66 +0xb1
2022/03/05 22:52:59 main.run()
2022/03/05 22:52:59 	github.com/wieku/danser-go/main.go:93 +0x25
2022/03/05 22:52:59 github.com/faiface/mainthread.Run.func1()
2022/03/05 22:52:59 	github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:37 +0x26
2022/03/05 22:52:59 created by github.com/faiface/mainthread.Run
2022/03/05 22:52:59 	github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:36 +0xbd
2022/03/05 22:52:59
```

**Computer configuration:**
OS: Arco Linux
CPU: Ryzen 7 1700 (OC at 3.85GHz)
GPU: Gtx 1660 Super

**Comment by MierenManz** [comment]
Nvm. Third party arch script that I use doesn't properly forward my input to the danser binary :/

Please disregard this "bug"
