### ISSUE TITLE
"no go files in directory" (mac)

### ISSUE THREAD

**Issue by CtrlAltWaverick** [Wieku/danser-go#29]
[user@computer] ~ % go get -u github.com/wieku/danser
package github.com/wieku/danser: no Go files in /Users/[user]/go/src/github.com/wieku/danser
[user@computer] ~ % cd ~/go/src/github.com/wieku/danser/
[user@computer] danser % go build
can't load package: package github.com/wieku/danser: no Go files in /Users/[user]/go/src/github.com/wieku/danser

**Comment by Wieku** [comment]
Crap, I forgot to fix the readme.
`go get -u github.com/wieku/danser-go`

**Comment by Wieku** [comment]
Fixed the readme, it should work now ;)

**Comment by CtrlAltWaverick** [comment]
[user@computer] ~ % go get -u github.com/wieku/danser-go
# github.com/go-gl/glfw/v3.2/glfw
In file included from go/src/github.com/go-gl/glfw/v3.2/glfw/c_glfw_darwin.go:8:
go/src/github.com/go-gl/glfw/v3.2/glfw/glfw/src/cocoa_window.m:989:9: warning: multiple methods named 'center' found [-Wobjc-multiple-method-names]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSCollectionViewCompositionalLayout.h:601:19: note: using
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AppKit.framework/Headers/NSWindow.h:312:1: note: also found
# github.com/wieku/danser-go/audio
ld: unknown option: -rpath=$ORIGIN
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Wieku** [comment]
Can you try now? I'm unable to test it myself as I don't own any device with MacOS onboard

**Comment by CtrlAltWaverick** [comment]
it opens now, but i'm getting a (probably unrelated) error:
`````
...
2020/08/17 16:03:08 Loading texture:  assets/textures/default-7.png
2020/08/17 16:03:09 Loading texture:  assets/textures/default-8.png
2020/08/17 16:03:09 Loading texture:  assets/textures/default-9.png
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x0]

runtime stack:
runtime.throw(0x4680059, 0x2a)
	/usr/local/go/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:679 +0x46a
runtime.asmcgocall(0x0, 0x46375c0)
	/usr/local/go/src/runtime/asm_amd64.s:659 +0x70

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x441e230, 0xc0004ccce0, 0x7fff39da9e5a)
	/usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc0004cccb0 sp=0xc0004ccc78 pc=0x400606b
github.com/go-gl/gl/v3.3-core/gl._Cfunc_glowFramebufferTextureLayerARB(0x0, 0x8ce000008d40, 0x6, 0xc000000000)
	_cgo_gotypes.go:7398 +0x45 fp=0xc0004ccce0 sp=0xc0004cccb0 pc=0x40ea865
github.com/go-gl/gl/v3.3-core/gl.FramebufferTextureLayerARB(...)
	/Users/[username]/go/src/github.com/go-gl/gl/v3.3-core/gl/package.go:9554
github.com/wieku/danser-go/render/framebuffer.NewFrame(0x780, 0x438, 0x101, 0xc0004da2a0)
	/Users/[username]/go/src/github.com/wieku/danser-go/render/framebuffer/framebuffer.go:30 +0xfb fp=0xc0004ccd20 sp=0xc0004ccce0 pc=0x41b87fb
github.com/wieku/danser-go/render.SetupSlider()
	/Users/[username]/go/src/github.com/wieku/danser-go/render/slider.go:53 +0x61d fp=0xc0004ccf28 sp=0xc0004ccd20 pc=0x41d781d
github.com/wieku/danser-go/states.NewPlayer(0xc000576380, 0x18)
	/Users/[username]/go/src/github.com/wieku/danser-go/states/player.go:83 +0x59 fp=0xc0004cd740 sp=0xc0004ccf28 pc=0x4410d69
main.run.func1()
	/Users/[username]/go/src/github.com/wieku/danser-go/main.go:182 +0x1338 fp=0xc0004cde98 sp=0xc0004cd740 pc=0x441ac48
github.com/faiface/mainthread.Call.func1()
	/Users/[username]/go/src/github.com/faiface/mainthread/mainthread.go:63 +0x2f fp=0xc0004cdec8 sp=0xc0004cde98 pc=0x40e8cbf
github.com/faiface/mainthread.Run(0x468d218)
	/Users/[username]/go/src/github.com/faiface/mainthread/mainthread.go:44 +0xbd fp=0xc0004cdf68 sp=0xc0004cdec8 pc=0x40e8a3d
main.main()
	/Users/[username]/go/src/github.com/wieku/danser-go/main.go:257 +0x48 fp=0xc0004cdf88 sp=0xc0004cdf68 pc=0x44198f8
runtime.main()
	/usr/local/go/src/runtime/proc.go:203 +0x1fa fp=0xc0004cdfe0 sp=0xc0004cdf88 pc=0x4037cda
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0004cdfe8 sp=0xc0004cdfe0 pc=0x40648b1

goroutine 19 [chan receive]:
github.com/faiface/mainthread.Call(0xc000110340)
	/Users/[username]/go/src/github.com/faiface/mainthread/mainthread.go:66 +0xc2
main.run()
	/Users/[username]/go/src/github.com/wieku/danser-go/main.go:36 +0x9c
github.com/faiface/mainthread.Run.func1(0x468d218, 0xc000128060)
	/Users/[username]/go/src/github.com/faiface/mainthread/mainthread.go:37 +0x27
created by github.com/faiface/mainthread.Run
	/Users/[username]/go/src/github.com/faiface/mainthread/mainthread.go:36 +0xb1

goroutine 20 [select]:
database/sql.(*DB).connectionOpener(0xc0001360c0, 0x471d320, 0xc00014c880)
	/usr/local/go/src/database/sql/sql.go:1071 +0xe8
created by database/sql.OpenDB
	/usr/local/go/src/database/sql/sql.go:742 +0x12a

**Comment by Wieku** [comment]
What GPU does your Mac have?

**Comment by Wieku** [comment]
Should be fixed now, wait for release

**Comment by Wieku** [comment]
Nevermind. Danser uses gl not supported by Mac OS. If you want to run danser, do it through Windows/Linux.
