### ISSUE TITLE
danser crashes with GL_ARB_direct_state_access error on Windows but...

### ISSUE THREAD

**Issue by GDPlayer** [Wieku/danser-go#319]
**Describe the bug**
danser crashes on Windows even though it runs fine on WSL. Unable to update graphics driver
**Logs**
```
2023/02/27 11:35:14 danser-go version: 0.8.4
2023/02/27 11:35:14 ApiConnector: Loading "C:\Users\ACER\Desktop\danser\settings\credentials.json"
2023/02/27 11:35:14 SettingsManager: Loading "C:\Users\ACER\Desktop\danser\settings\default.json"
2023/02/27 11:35:14 SettingsManager: "C:\Users\ACER\Desktop\danser\settings\default.json" loaded!
2023/02/27 11:35:15 GLFW initialized!
2023/02/27 11:35:15 Initializing OpenGL...
2023/02/27 11:35:15 panic: Failed to initialize OpenGL: your GPU does not support one or more required OpenGL extensions: [GL_ARB_direct_state_access]. Please update your graphics drivers or upgrade your GPU
2023/02/27 11:35:15 goroutine 17 [running, locked to thread]:
2023/02/27 11:35:15 github.com/wieku/danser-go/launcher.(*launcher).startGLFW(0xc0000a8000)
2023/02/27 11:35:15 	github.com/wieku/danser-go/launcher/launcher.go:359 +0x8a5
2023/02/27 11:35:15 github.com/faiface/mainthread.Call.func1()
2023/02/27 11:35:15 	github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:63 +0x26
2023/02/27 11:35:15 github.com/faiface/mainthread.Run(0xc0000882f0)
2023/02/27 11:35:15 	github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:44 +0xc4
2023/02/27 11:35:15 github.com/wieku/danser-go/launcher.StartLauncher()
2023/02/27 11:35:15 	github.com/wieku/danser-go/launcher/launcher.go:245 +0x6f0
2023/02/27 11:35:15 main.danserMain(0x1, {0x23797426080?, 0x0?, 0x1?})
2023/02/27 11:35:15 	github.com/wieku/danser-go/mainshared.go:18 +0x69
2023/02/27 11:35:15 
2023/02/27 11:35:15 goroutine 20 [chan receive]:
2023/02/27 11:35:15 github.com/faiface/mainthread.Call(0xc00004f650)
2023/02/27 11:35:15 	github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:66 +0xb1
2023/02/27 11:35:15 github.com/wieku/danser-go/launcher.StartLauncher.func2()
2023/02/27 11:35:15 	github.com/wieku/danser-go/launcher/launcher.go:253 +0x85
2023/02/27 11:35:15 github.com/faiface/mainthread.Run.func1()
2023/02/27 11:35:15 	github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:37 +0x26
2023/02/27 11:35:15 created by github.com/faiface/mainthread.Run
2023/02/27 11:35:15 	github.com/faiface/mainthread@v0.0.0-20171120011319-8b78f0a41ae3/mainthread.go:36 +0xb8
2023/02/27 11:35:15 
```
**Computer configuration:**
Operating System: Windows 10
CPU: Intel Celeron N3450
GPU: Intel HD Graphics 500

**Comment by PercyDan54** [comment]
It told you what to do.
`Please update your graphics drivers or upgrade your GPU`

**Comment by GDPlayer** [comment]
> It told you what to do. `Please update your graphics drivers or upgrade your GPU`

i **CANT** its in the post

**Comment by MelonIs45** [comment]
If you cant update the driver than what else do you think can be done to rectify this issue? You'd be more likely to know

**Comment by GDPlayer** [comment]
it works on wsl ubuntu but it doenst work on native, btw using wsl is slow as heck

**Comment by vipotaenko02** [comment]
> it works on wsl ubuntu but it doenst work on native, btw using wsl is slow as heck

Your GPU just doesn't support OpenGL 4.5, which is required to use danser. Through WSL it is working via emulation, so it is slow. You can find OpenGL implementation that will run on a CPU and danser will work, but very slow (about half a day for one 1080p60 video).
